FROM nginx:alpine

# Install openssl
RUN apk add --no-cache openssl

# Set the working directory
WORKDIR /etc/ssl/certs

# Generate a self-signed SSL certificate
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout localhost.key -out localhost.crt -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com"

# Copy the Nginx configuration file
COPY nginx.conf /etc/nginx/conf.d/default.conf